apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.IMAGE_NAME }}
  name: {{ .Values.IMAGE_NAME }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.IMAGE_NAME }}
  template:
    metadata:
      labels:
        app: {{ .Values.IMAGE_NAME }}
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
        - 0    
      containers:
        - name: {{ .Values.IMAGE_NAME }}
          image: "{{ .Values.REPOSITORY }}/{{ .Values.IMAGE_NAME}}:{{ .Values.APP_VERSION }}" 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http-grafana
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1            
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: {{ .Values.PV_NAME }}
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: {{ .Values.PV_NAME }}
          persistentVolumeClaim:
            claimName: {{ .Values.PVC_NAME }}