apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.PVC_NAME }}
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: "{{ .Values.PV_NAME }}"
  storageClassName: ""