apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.PV_NAME }}
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    server: {{ .Values.NFS_SERVER }}
    path: "{{ .Values.NFS_PATH }}"
  persistentVolumeReclaimPolicy: "Retain"