apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.VOLUMES.PV_NAME }}
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ .Values.VOLUMES.CAPACITY }}
  nfs:
    server: {{ .Values.VOLUMES.NFS_SERVER }}
    path: "{{ .Values.VOLUMES.NFS_PATH }}"
  persistentVolumeReclaimPolicy: "Retain"