apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.APP.IMAGE_NAME }}
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector:
    app: {{ .Values.APP.IMAGE_NAME }}
  type: NodePort
  ports:
    - port: {{ .Values.SERVICE.TARGET_PORT_HTTP }}
      name: http
      targetPort: {{ .Values.SERVICE.TARGET_PORT_HTTP }}
      nodePort: {{ .Values.SERVICE.NODE_PORT_HTTP }}
    - port: {{ .Values.SERVICE.TARGET_PORT_SSH }}
      targetPort: {{ .Values.SERVICE.TARGET_PORT_SSH }}
      nodePort: {{ .Values.SERVICE.NODE_PORT_SSH}}
      name: ssh