APP:
  IMAGE_NAME: "gerrit"
  APP_VERSION: "3.3.2"
  NAMESPACE: ""
  REPLICAS: "1"
  WEB_URL: "http://192.168.0.56:32003"
  HTTPD_LISTENURL: "proxy-http://*:8080"
  AUTH_TYPE: "OAUTH"
  OAUTH_KEYCLOAK_CLIENT_ID: "gerrit"
  OAUTH_KEYCLOAK_CLIENT_SECRET: "keycloak-gerrit"
  OAUTH_KEYCLOAK_REALM: "kubernetes"
  OAUTH_KEYCLOAK_ROOT_URL: "http://192.168.0.55:32009"
  REPOSITORY: "openfrontier/gerrit:3.3.2"
  NODE_SELECTOR: "worker-node-4"
SERVICE:
  SERVICE_TYPE: "NodePort"
  TARGET_PORT_HTTP: "8080"
  TARGET_PORT_SSH: "30289"
  NODE_PORT_HTTP: "32003"
  NODE_PORT_SSH: "30289"
VOLUMES:
  PV_NAME: "gerrit-data-pv"
  PVC_NAME: "gerrit-data-pvc"
  NFS_SERVER: "192.168.0.150"
  NFS_PATH: "/srv/gerrit-data"
  CAPACITY: "10Gi"